# Generated by Django 3.2.5 on 2023-05-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
    ]
