# Generated by Django 3.2.5 on 2023-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
