# Generated by Django 3.2.5 on 2023-05-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employee-avatars/'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_employee', to='employee.employee', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
