# Generated by Django 3.2.5 on 2023-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20230524_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
